FROM jumanjiman/duoauthproxy:latest

USER 0
RUN chmod 777 /etc/duoauthproxy -R
RUN /opt/duoauthproxy/bin/authproxy_update_sso_enrollment_code eyJhcGlfaG9zdCI6ICJzc28tMDQzYzQ5Y2Muc3NvLmR1b3NlY3VyaXR5LmNvbSIsICJzaWduaW5nX3NrZXkiOiAiTnVuZjNzWnc0SFF4a0RNZ01tdDZlYmtjV3BZVjMwMk5lT2ZFLTJsN3lPTT0iLCAiZW5jcnlwdGlvbl9za2V5IjogIllnWG0yN2FZckZVME9FZHhWY3c2QUIwcGU3WWN3Z1dPYnV1MmFPR0ZrRFU9IiwgInByb3h5X2tleSI6ICJQUlRIU0tJMTFMRzZCNkdSVzhVMCJ9
RUN chown duo:duo /etc/duoauthproxy/secrets
USER duo