FROM jumanjiman/duoauthproxy:latest

USER 0
RUN chmod 777 /etc/duoauthproxy -R
RUN /opt/duoauthproxy/bin/authproxy_update_sso_enrollment_code eyJhcGlfaG9zdCI6ICJzc28tMDQzYzQ5Y2Muc3NvLmR1b3NlY3VyaXR5LmNvbSIsICJzaWduaW5nX3NrZXkiOiAiMDRoMEVRdEtJR2ZrQzg0cl9QbDVSSmtkT2xibzRNaDF3WmNYZ29mZDR3az0iLCAiZW5jcnlwdGlvbl9za2V5IjogIk5qbEh4REI4cGZ6QmFaNDltRjNySUFtanZ0MVU4UjV3UHNrNHlLcFhJbW89IiwgInByb3h5X2tleSI6ICJQUjU3NVpGMDlPRDk0QUxGR1lKVSJ9
RUN chown duo:duo /etc/duoauthproxy/secrets
USER duo